import React from 'react';

const Footer: React.FC = () => {
  return (
    <footer className="bg-hop-black text-white py-16 px-6">
      <div className="max-w-6xl mx-auto flex flex-col md:flex-row justify-between items-center gap-8">
        <div className="text-center md:text-left">
          <p className="font-heading font-bold text-2xl mb-2">Žiga Zois</p>
          <p className="text-sm text-gray-400">&copy; 2026 HopGuides & Prirodoslovni muzej Slovenije.</p>
        </div>
        
        <div className="flex gap-6 text-sm font-bold">
           <span className="hover:text-hop-primary cursor-pointer transition-colors">Vse pravice pridržane.</span>
        </div>

        <div className="text-xs text-gray-500 border border-gray-800 px-4 py-2 rounded-full">
          Generated by Case Study Zois AI
        </div>
      </div>
    </footer>
  );
};

export default Footer;